Repository CODE-LG/code-l-server, pull requests merged in 2025-07, with the labels that each got.

#65 [refactor/#64] 멤버 상태값 조건 추가
  src/main/kotlin/codel/member/business/MemberService.kt
  src/main/kotlin/codel/member/infrastructure/MemberJpaRepository.kt
Labels: Refactor

#69 [refactor/#68] dto 네이밍 변경
  src/main/kotlin/codel/member/presentation/MemberController.kt
  src/main/kotlin/codel/member/presentation/response/MemberRecommendResponses.kt
  src/main/kotlin/codel/member/presentation/response/MemberResponse.kt
  src/main/kotlin/codel/member/presentation/swagger/MemberControllerSwagger.kt
Labels: Refactor

#67 [refactor/#66] 채팅방 목록 조회에 페이지네이션 추가
  src/main/kotlin/codel/chat/business/ChatService.kt
  src/main/kotlin/codel/chat/domain/Chat.kt
  src/main/kotlin/codel/chat/domain/ChatRoom.kt
  src/main/kotlin/codel/chat/domain/ChatRoomMember.kt
  src/main/kotlin/codel/chat/infrastructure/ChatJpaRepository.kt
  src/main/kotlin/codel/chat/infrastructure/ChatRoomJpaRepository.kt
  src/main/kotlin/codel/chat/infrastructure/ChatRoomMemberJpaRepository.kt
  src/main/kotlin/codel/chat/presentation/ChatController.kt
  src/main/kotlin/codel/chat/presentation/response/ChatResponse.kt
  src/main/kotlin/codel/chat/presentation/response/ChatResponses.kt
  src/main/kotlin/codel/chat/presentation/response/ChatRoomResponse.kt
  src/main/kotlin/codel/chat/presentation/response/ChatRoomResponses.kt
  src/main/kotlin/codel/chat/presentation/response/PartnerResponse.kt
  src/main/kotlin/codel/chat/presentation/swagger/ChatControllerSwagger.kt
  src/main/kotlin/codel/chat/repository/ChatRepository.kt
  src/main/kotlin/codel/chat/repository/ChatRoomRepository.kt
  src/main/kotlin/codel/common/domain/BaseTimeEntity.kt
  src/main/kotlin/codel/config/JpaConfig.kt
Labels: Feature

#80 [feature/#79] 채팅 정렬 수정, seed 파라미터 바인딩 수정
  src/main/kotlin/codel/chat/repository/ChatRepository.kt
  src/main/kotlin/codel/member/infrastructure/MemberJpaRepository.kt
Labels: Feature

#90 [refactor#88] : 배열 형태의 응답 데이터 일관성 수정
  src/main/kotlin/codel/member/presentation/response/MemberRecommendResponses.kt
Labels: Refactor

#95 [feature/#94] 받은 시그널 조회 기능
  src/main/kotlin/codel/signal/business/SignalService.kt
  src/main/kotlin/codel/signal/domain/Signal.kt
  src/main/kotlin/codel/signal/infrastructure/SignalRepository.kt
  src/main/kotlin/codel/signal/presentation/SignalController.kt
  src/main/kotlin/codel/signal/presentation/response/ReceivedSignalResponse.kt
  src/test/kotlin/codel/signal/business/SignalServiceTest.kt
Labels: Feature

#97 [feature/#96] 보낸 시그널 목록 조회
  src/main/kotlin/codel/signal/business/SignalService.kt
  src/main/kotlin/codel/signal/infrastructure/SignalJpaRepository.kt
  src/main/kotlin/codel/signal/presentation/SignalController.kt
  src/main/kotlin/codel/signal/presentation/response/SignalMemberResponse.kt
  src/test/kotlin/codel/signal/business/SignalServiceTest.kt
Labels: Feature

#112 [feature/#110] 시그널 매칭성공 조회 API
  src/main/kotlin/codel/signal/business/SignalService.kt
  src/main/kotlin/codel/signal/domain/Signal.kt
  src/main/kotlin/codel/signal/domain/SignalStatus.kt
  src/main/kotlin/codel/signal/presentation/SignalController.kt
  src/main/kotlin/codel/signal/presentation/swagger/SignalControllerSwagger.kt
  src/test/kotlin/codel/signal/business/SignalServiceTest.kt
Labels: Feature

#113 [feature/#111]
  src/main/kotlin/codel/chat/business/ChatService.kt
  src/main/kotlin/codel/chat/domain/ChatRoom.kt
  src/main/kotlin/codel/chat/domain/ChatRoomStatus.kt
  src/main/kotlin/codel/chat/presentation/ChatController.kt
  src/main/kotlin/codel/chat/repository/ChatRoomRepository.kt
  src/test/kotlin/codel/chat/domain/ChatRoomTest.kt
Labels: Feature

#119 [fix] 테스트 수정
  src/test/kotlin/codel/signal/business/SignalServiceTest.kt
Labels: Fix

#130 [docs#129] Swagger 문서화 : getUnlockedSignal, hideSignal
  src/main/kotlin/codel/signal/presentation/SignalController.kt
  src/main/kotlin/codel/signal/presentation/swagger/SignalControllerSwagger.kt
Labels: Docs

#133 [refactor/#132] 시그널 코드 리팩토링
  src/main/kotlin/codel/signal/business/SignalService.kt
  src/main/kotlin/codel/signal/domain/Signal.kt
  src/main/kotlin/codel/signal/presentation/response/SignalResponse.kt
  src/test/kotlin/codel/member/business/MemberServiceTest.kt
  src/test/kotlin/codel/signal/business/SignalServiceTest.kt
Labels: Feature

#136 [fix/#135] 머지 충돌 해결
  src/main/kotlin/codel/signal/business/SignalService.kt
  src/main/kotlin/codel/signal/domain/Signal.kt
  src/test/kotlin/codel/signal/business/SignalServiceTest.kt
Labels: Bug

#140 [docs] 회원 상세 조회 API 문서화
  src/main/kotlin/codel/member/presentation/MemberController.kt
  src/main/kotlin/codel/member/presentation/swagger/MemberControllerSwagger.kt
Labels: Docs

#143 [feature/#142] 채팅방 목록 조회 API 수정
  src/main/kotlin/codel/chat/business/ChatService.kt
  src/main/kotlin/codel/chat/domain/ChatRoom.kt
  src/main/kotlin/codel/chat/infrastructure/ChatJpaRepository.kt
  src/main/kotlin/codel/chat/presentation/ChatController.kt
  src/main/kotlin/codel/chat/presentation/request/ChatLogRequest.kt
  src/main/kotlin/codel/chat/presentation/response/ChatRoomResponse.kt
  src/main/kotlin/codel/chat/presentation/swagger/ChatControllerSwagger.kt
  src/main/kotlin/codel/chat/repository/ChatRepository.kt
  src/main/kotlin/codel/member/presentation/MemberController.kt
  src/main/kotlin/codel/member/presentation/swagger/MemberControllerSwagger.kt
Labels: Bug

#151 [docs] 신고하기 API 문서화
  src/main/kotlin/codel/report/presentation/ReportController.kt
  src/main/kotlin/codel/report/presentation/swagger/ReportControllerSwagger.kt
Labels: Docs

#155 [feat] 차단해제 API
  src/main/kotlin/codel/block/business/BlockService.kt
  src/main/kotlin/codel/block/domain/BlockMemberRelation.kt
  src/main/kotlin/codel/block/infrastructure/BlockMemberJpaRepository.kt
  src/main/kotlin/codel/block/infrastructure/BlockMemberRelationJpaRepository.kt
  src/main/kotlin/codel/block/presentation/BlockController.kt
  src/main/kotlin/codel/block/presentation/swagger/BlockControllerSwggger.kt
Labels: Feature

#159 [feat] MemberProfileDetailResponse 응답 값에 isUnlocked 필드 추가
  src/main/kotlin/codel/chat/business/ChatService.kt
  src/main/kotlin/codel/chat/infrastructure/ChatRoomJpaRepository.kt
  src/main/kotlin/codel/member/business/MemberService.kt
  src/main/kotlin/codel/member/presentation/response/MemberProfileDetailResponse.kt
Labels: Feature

#160 [feature/#153] 회원가입 알림기능 생성
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  src/main/kotlin/codel/admin/business/AdminService.kt
  src/main/kotlin/codel/admin/presentation/AdminController.kt
  src/main/kotlin/codel/chat/infrastructure/ChatRoomJpaRepository.kt
  src/main/kotlin/codel/config/RestTemplateConfig.kt
  src/main/kotlin/codel/member/business/MemberService.kt
  src/main/kotlin/codel/notification/business/NotificationService.kt
  src/main/kotlin/codel/notification/domain/Notification.kt
  src/main/kotlin/codel/notification/domain/NotificationType.kt
  src/main/kotlin/codel/notification/domain/sender/DiscordNotificationSender.kt
  src/main/kotlin/codel/notification/domain/sender/FcmNotificationSender.kt
  src/main/kotlin/codel/notification/domain/sender/NotificationSender.kt
  src/main/resources/templates/memberDetail.html
  src/test/kotlin/codel/config/TestFixture.kt
  src/test/kotlin/codel/member/business/MemberServiceTest.kt
Labels: Feature
